# Generated by Django 3.2.3 on 2021-05-18 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_polls', '0002_alter_pollanswer_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollanswer',
            name='poll_question',
        ),
        migrations.RemoveField(
            model_name='pollquestion',
            name='poll',
        ),
    ]
