# Generated by Django 3.2.3 on 2021-05-18 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_polls', '0003_auto_20210518_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollanswer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='my_polls.pollquestion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pollquestion',
            name='poll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='my_polls.poll'),
            preserve_default=False,
        ),
    ]
