# Generated by Django 3.2.3 on 2021-05-20 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_polls', '0005_alter_poll_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='answered_by',
            field=models.ManyToManyField(related_name='answered_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
